<a href="https://colab.research.google.com/github/HasanMdKamrul/DataScienceProject/blob/main/data_preprocessing_tools(using%20a%20simple%20dataset).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [32]:
import numpy as np # ML models will expect some numpy models as their inputs
import matplotlib.pyplot as plt # Allows to plot charts and graphs
import pandas as pd # import datasets + also create the matrix of features and the dependent variable vector

## Importing the dataset

In [33]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values # Matrix of features X (Independent Variables)
y = dataset.iloc[:,-1].values # Dependent Variables Y (Desicions)

In [34]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [35]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [36]:
from sklearn.impute import SimpleImputer # Class for missing data handelling as  their mean value replacement standard
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean') # instance of that class and 2 arguments(1.find the missing values 2.What with we're gonna change here mean)
imputer.fit(x[:,1:3]) # fit method find the avg or mean of the following columns
x[:,1:3] = imputer.transform(x[:,1:3]) # Replace the missing values of the data and store in a updated one

In [37]:
print(x) # Printing of the updated values at the missing places

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [38]:
from sklearn.compose import ColumnTransformer # this class will encode the string into binary vector here our country column
from sklearn.preprocessing import OneHotEncoder # To encode we need a class to binary vector which is OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough') # instance = (2 arguments 1. transformers(1.What type of method we applied to chage our data,here encoder2.Who will do that job done, OneHotEncoder(),3.Where we applied the encoding, column[0]) 2. remainder(passthrough means it won't affect our other independet varriables and regardless keep them as it is))
x = np.array(ct.fit_transform(x)) # Not do like privious step bcoz now we have ColumnTransformer class which has built in fit transform method in it, which done  the job of fitting the changed values at our updated matrix of features or the independent part

In [39]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [40]:
from sklearn.preprocessing import LabelEncoder # This encoder used when decision depends on 2 values like yes/no, OneHotEncoder has 3 values or more values to deal
le = LabelEncoder()# No arguments in the () bcoz it has only coloum to work with
y = le.fit_transform(y) # dependent var dosen't need to be np array thats why we avoided unlike the prior one

In [41]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [42]:
from sklearn.model_selection import train_test_split #train_test method will split the train and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=1) # train_test method returns 4 variable independent train(80% data), independent test(20%data), dependent train and test sets

In [43]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [44]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [45]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [46]:
print(y_test)

[0 1]


In [ ]:
# Why we have to do the feature scalling after the split?
# if we do the feature scalling before the split the information will leak from the train set to test set
# Where the test set is completely new observations depending on the train set data or results 
# so before tain the train set if we feature scale it will affect our test set predictions or observations

## Feature Scaling

In [ ]:
# Why we feature scale?
# Becoz we don't want to dominate few important features to be dominated by the others which has no significant play in our machine learning model
# It is not necessary for all the ML models but to avoid dominanace one feature to another we need to scale all the features in the same scale
# Two method to feature scaling 1.Standardisation 2. Normalisation
# Normalisation is for normal distribution of data but Standardisation will fit in all the situations(recommended to use it)
# What we'll do here we first apply the standardisation with the x_train data for our x_train and we'll use the same x_train data for out x_test as well, So we'll not use the x_test data to calculate the x_test standardisation
# Standardisation, Xstand = x-mean(x/standard deviation(x)--->root square varriance). ---> data varried between -3 to +3
# Xnorm = x-min(x)/max(x)-min(x) ----> data varried between 0 and 1 

In [47]:
from sklearn.preprocessing import StandardScaler # StandardScaler class will do the standardisation
sc = StandardScaler() # Creating instance with no arguments bcoz only x values to take see the formula
x_train[:,3:] = sc.fit_transform(x_train[:,3:])# fit will give the mean and standard deviation but tranform will provide the whole equation result
x_test[:,3:] = sc.transform(x_test[:,3:]) # only the transform used in test set while the mean and stndard deviation is used from the x_train set

In [48]:
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [49]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
