<a href="https://colab.research.google.com/github/HasanMdKamrul/DataScienceProject/blob/main/Multiple_linear_regression(With%20single%20prediction%20and%20it's%20co-efficients).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Multiple Linear Regression

## Importing the libraries

In [ ]:
#Our first step is to see the dataset and lookthrough what kind of data preprocessing is needed
#When we look through our current dataset we found out that there is no missing data but we have one catagorical data or in other word the dummy veriable in the independent variable
#Why we don't need to apply the feature scalling ?--> Bcz co-efficients corresponding the varriables will compensate the values of the independent varriables to the scale perametre.
#Do we need to check the assamption of the multiple linear regression? --> No, bcz when you fit all your varriable in the multiple linear regression model if it's not linear it will performe poorly from there you'll know that the assamption aren't fullfiled.

In [14]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
#Importing all the necessary libraries

## Importing the dataset

In [15]:
dataset = pd.read_csv('50_Startups.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
#Importing dataset and split the values into features of matrix X and y vector variable as the dependent variable here as profit

In [16]:
print(X)

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']
 [131876.9 99814.71 362861.36 'New York']
 [134615.46 147198.87 127716.82 'California']
 [130298.13 145530.06 323876.68 'Florida']
 [120542.52 148718.95 311613.29 'New York']
 [123334.88 108679.17 304981.62 'California']
 [101913.08 110594.11 229160.95 'Florida']
 [100671.96 91790.61 249744.55 'California']
 [93863.75 127320.38 249839.44 'Florida']
 [91992.39 135495.07 252664.93 'California']
 [119943.24 156547.42 256512.92 'Florida']
 [114523.61 122616.84 261776.23 'New York']
 [78013.11 121597.55 264346.06 'California']
 [94657.16 145077.58 282574.31 'New York']
 [91749.16 114175.79 294919.57 'Florida']
 [86419.7 153514.11 0.0 'New York']
 [76253.86 113867.3 298664.47 'California']
 [78389.47 153773.43 299737.29 'New York']
 [73994.56 122782.75 303319.26 'Florida']
 [67532

In [17]:
print(y)

[192261.83 191792.06 191050.39 182901.99 166187.94 156991.12 156122.51
 155752.6  152211.77 149759.96 146121.95 144259.4  141585.52 134307.35
 132602.65 129917.04 126992.93 125370.37 124266.9  122776.86 118474.03
 111313.02 110352.25 108733.99 108552.04 107404.34 105733.54 105008.31
 103282.38 101004.64  99937.59  97483.56  97427.84  96778.92  96712.8
  96479.51  90708.19  89949.14  81229.06  81005.76  78239.91  77798.83
  71498.49  69758.98  65200.33  64926.08  49490.75  42559.73  35673.41
  14681.4 ]


## Encoding categorical data

In [18]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [19]:
print(X)

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 119943.24 156547.42 256512.92]
 [0.0 0.0 1.0 114523.61 122616.84 261776.23]
 [1.0 0.0 0.0 78013.11 121597.55 264346.06]
 [0.0 0.0 1.0 94657.16 145077.58 282574.31]
 [0.0 1.0 0.0 91749.16 114175.79 294919.57]
 [0.0 0.0 1.0 86419.7 153514.11 0.0]
 [1.0 0.0 0.0 76253.86 113867.3 298664.47]
 [0.0 0.0 1.0 78389.47 153773.43 299737.29]
 [0.0 1.0 0.0 73994.56 122782.75 3

In [ ]:
# Since we have no missing data but the catagorical 3 variables so we use OneHotEncoding instead of the label encoder which only catagories variables into zeros and ones

## Splitting the dataset into the Training set and Test set

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
# Dataset differentiate into test and training sets

## Training the Multiple Linear Regression model on the Training set

In [21]:
from sklearn.linear_model import LinearRegression # This LinearRegression class will avoid the dummy variable trap automatically as well as automatically choose the best features for us. --> No need to do the stuffs line backword elemination, forword selection etc.
regressor = LinearRegression() # Multiple linear regression model is built as like simple linear regression
regressor.fit(X_train, y_train) # Fit method just train our model. 

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Predicting the Test set results

In [30]:
y_pred = regressor.predict(X_test)
#print(y_pred)
#print(y_test)
np.set_printoptions(precision=2) # It just help us to take 2 values after the decimal
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # If we put zero in the last possition instead of 1 it will concatinate vertically but we put 1 so that it concatinated horizontally.---> fist col predicted value , second col real profit values

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]


In [ ]:
# What reshape is doing it converts the horizontal arrays to vertical one

For the single prediction, where R&D Spend= 160000, Adminstration Spend= 130000, Marketing Spend=300000 and state = california

In [31]:
y_pred = regressor.predict(([[1,0,0,160000,130000,300000]])) #(predict function or method expect 2D array as it's input so we put [[]] and california after catagorical data produced dummy variables as 100)
print(y_pred)

[181566.92]


In [32]:
print(regressor.coef_) # Coefficients ---> y_profit = 8.66e+01*Dummyset1*-8.73e+02*Dummyset2*7.86e+02*Dummyset3*7.73e-01*R&D+3.29e-02*Admin+3.66e-02*Marketing+42457.52(intercept or the constant)

[ 8.66e+01 -8.73e+02  7.86e+02  7.73e-01  3.29e-02  3.66e-02]


In [33]:
print(regressor.intercept_) # Used the intercept function to find out the intercept or the constant

42467.52924853204
