<a href="https://colab.research.google.com/github/HasanMdKamrul/DataScienceProject/blob/main/Random_forest_regression(Code%20template_Data.csv).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Random Forest Regression

## Importing the libraries

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [27]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

## Splitting the dataset into the Training set and Test set

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Training the Random Forest Regression model on the whole dataset

In [29]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

## Predicting the Test set results

In [30]:
y_pred = regressor.predict(X_test) # Predicted result considering the X_test
print(y_pred) # Predicted result in a single row where colmns are multiple
print(y_test) # Original testset result in a single row where colmns are multiple
np.set_printoptions(precision=2) # This will set the 2 points after the . as choose the precision = 2
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)) # np.concatenate((y_pred.reshape(len(y_pred),1)---> Took the length of y_pred, y_test also later and make the row to column and size of the colmn is 1---> and show them in a 2-D matrix 

[433.78 457.99 463.14 ... 470.16 439.51 460.32]
[431.23 460.01 461.14 ... 473.26 438.   463.28]
[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


## Evaluating the Model Performance

In [31]:
from sklearn.metrics import r2_score # From sklearn matrics module I imported the r2_score---> r_squared value to evaluated. r_2 scare more tends to 1 the better result and better precision
r2_score(y_test, y_pred) # r_2 score according to the true result of the y_testset and the predicted y_pred

0.9615980699813017